### ISSUE TITLE
Asset unconnected ports 

### ISSUE THREAD

**Issue by KobusVanRooyen** [Multi-Energy-Systems-Optimization/mesido#10]
- When a network is optimized and the ESDL file is updated, then the asset ports all seem disconnected.
- Attached is a example ESDL file when the test_multiple_in_and_out_port_components.py is used to run test_heat_pump(..)
[heat_pump_GrowOptimized.txt](https://github.com/Multi-Energy-Systems-Optimization/mesido/files/14770777/heat_pump_GrowOptimized.txt)

**Comment by jimrojerTNO** [comment]
Check if the deepcopy is the cause

**Comment by JimRojer** [comment]
This issue can be closed? @KobusVanRooyen
