### ISSUE TITLE
Clarify the license is LGPLv3 and not GPLv3

### ISSUE THREAD

**Issue by lfse-slafleur** [Multi-Energy-Systems-Optimization/mesido#105]
Currently the license is specified in COPYING and COPYING.LESSER which contains respectively the GPLv3 and LGPLv3. The license should be LGPLv3 and not GPLv3 but GPLv3 is meant as as a reference as LGPLv3 directly references the GPLv3 license. We need to clarify that the license is LGPLv3 and that the GPLv3 is only added as a reference. Also use the LICENSE file instead of COPYING as that is the current known convention.

**Comment by FJanssen-TNO** [comment]
@lfse-slafleur I believe this issue can be closed with the PR# 116 and 117.

**Comment by KobusVanRooyen** [comment]
Code updated
