### ISSUE TITLE
Investigating where other time is lost before starting goal programming

### ISSUE THREAD

**Issue by jimrojerTNO** [Multi-Energy-Systems-Optimization/mesido#53]
use Jan esdl for debugging here

**Comment by KobusVanRooyen** [comment]
[DH_Jan with return network V3_20240425.txt](https://github.com/Multi-Energy-Systems-Optimization/mesido/files/15128491/DH_Jan.with.return.network.V3_20240425.txt)

**Comment by KobusVanRooyen** [comment]
Branch read for review
